[project]
name = "mock-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=40.1.0",
    "fastapi>=0.128.0",
    "kagglehub>=0.4.0",
    "standard-imghdr>=3.13.0",
    "uvicorn>=0.40.0",
]
